apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: LiteTopic
metadata:
  name: example-reservation
spec:
  forProvider:
    zone: us-central1-a
    partitionConfig:
    - count: 1
    reservationConfig:
    - throughputReservationRef:
        name: example
    retentionConfig:
    - perPartitionBytes: "32212254720"
