apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Schema
metadata:
  name: example
spec:
  forProvider:
    definition: |
      {
        "type" : "record",
        "name" : "Avro",
        "fields" : [
          {
            "name" : "StringField",
            "type" : "string"
          },
          {
            "name" : "IntField",
            "type" : "int"
          }
        ]
      }
    type: AVRO
