apiVersion: iap.gcp.upbound.io/v1beta1
kind: WebIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: iap/v1beta1/webiammember
  labels:
    testing.upbound.io/example-name: web-iam
  name: web-iam
spec:
  forProvider:
    member: "${data.google_iam_member.member}"
    role: "roles/iap.httpsResourceAccessor"
