apiVersion: firebaserules.gcp.upbound.io/v1beta1
kind: Release
metadata:
  annotations:
    meta.upbound.io/example-id: firebaserules/v1beta1/release
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    project: my-project-name
    rulesetNameSelector:
      matchLabels:
        testing.upbound.io/example-name: basic

---

apiVersion: firebaserules.gcp.upbound.io/v1beta1
kind: Ruleset
metadata:
  annotations:
    meta.upbound.io/example-id: firebaserules/v1beta1/release
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    project: my-project-name
    source:
    - files:
      - content: 'service cloud.firestore {match /databases/{database}/documents {
          match /{document=**} { allow read, write: if false; } } }'
        fingerprint: ""
        name: firestore.rules
      language: ""

---

apiVersion: firebaserules.gcp.upbound.io/v1beta1
kind: Ruleset
metadata:
  annotations:
    meta.upbound.io/example-id: firebaserules/v1beta1/release
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
spec:
  forProvider:
    project: my-project-name
    source:
    - files:
      - content: 'service cloud.firestore {match /databases/{database}/documents {
          match /{document=**} { allow read, write: if false; } } }'
        name: firestore.rules

---

