apiVersion: privateca.gcp.upbound.io/v1beta1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: privateca/v1beta1/certificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificateAuthoritySelector:
      matchLabels:
        testing.upbound.io/example-name: test-ca
    config:
    - publicKey:
      - format: PEM
        keySecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
      subjectConfig:
      - subject:
        - commonName: san1.example.com
          countryCode: us
          locality: mountain view
          organization: google
          organizationalUnit: enterprise
          province: california
          streetAddress: 1600 amphitheatre parkway
        subjectAltName:
        - emailAddresses:
          - email@example.com
          ipAddresses:
          - 127.0.0.1
          uris:
          - http://www.ietf.org/rfc/rfc3986.txt
      x509Config:
      - caOptions:
        - isCa: false
        keyUsage:
        - baseKeyUsage:
          - crlSign: false
            decipherOnly: false
          extendedKeyUsage:
          - serverAuth: false
    lifetime: 860s
    location: us-central1
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: privateca.gcp.upbound.io/v1beta1
kind: CertificateAuthority
metadata:
  annotations:
    meta.upbound.io/example-id: privateca/v1beta1/certificate
  labels:
    testing.upbound.io/example-name: test-ca
  name: test-ca
spec:
  forProvider:
    config:
    - subjectConfig:
      - subject:
        - commonName: my-certificate-authority
          organization: HashiCorp
        subjectAltName:
        - dnsNames:
          - hashicorp.com
      x509Config:
      - caOptions:
        - isCa: true
        keyUsage:
        - baseKeyUsage:
          - certSign: true
            crlSign: true
          extendedKeyUsage:
          - serverAuth: true
    deletionProtection: false
    ignoreActiveCertificatesOnDeletion: true
    keySpec:
    - algorithm: RSA_PKCS1_4096_SHA256
    location: us-central1
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skipGracePeriod: true

---

