apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: OrganizationIAMCustomRole
metadata:
  name: example
spec:
  forProvider:
    description: A description
    orgId: "123456789"
    permissions:
    - iam.roles.list
    - iam.roles.create
    - iam.roles.delete
    roleId: myCustomRole
    title: My Custom Role
