apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: OrganizationIAMPolicy
metadata:
  labels:
    testing.upbound.io/example-name: organization
  name: organization
spec:
  forProvider:
    orgId: your-organization-id
    policyData: ${data.google_iam_policy.admin.policy_data}

---

