apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectUsageExportBucket
metadata:
  name: example
spec:
  forProvider:
    bucketNameRef:
      name: example
    projectRef:
      name: example
