apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMPolicy
metadata:
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    policyData: ${data.google_iam_policy.admin.policy_data}
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

