apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectDefaultServiceAccounts
metadata:
  labels:
    testing.upbound.io/example-name: my_project
  name: my-project
spec:
  forProvider:
    action: DELETE
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

