apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMPolicy
metadata:
  labels:
    testing.upbound.io/example-name: admin-account-iam
  name: admin-account-iam
spec:
  forProvider:
    policyData: ${data.google_iam_policy.admin.policy_data}
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: sa

---

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/example-name: sa
  name: sa
spec:
  forProvider:
    displayName: A service account that only Jane can interact with

---

