apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/example-name: service_account
  name: service-account
spec:
  forProvider:
    displayName: Service Account

---

