apiVersion: dns.gcp.upbound.io/v1beta1
kind: Policy
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "One or more Networks must exist and match references set in spec.forProvider.networks[].networkRef.name"
spec:
  forProvider:
    alternativeNameServerConfig:
    - targetNameServers:
      - forwardingPath: private
        ipv4Address: 172.16.1.10
      - ipv4Address: 172.16.1.20
    enableInboundForwarding: true
    enableLogging: true
    networks:
    - networkRef:
        name: example
