apiVersion: dns.gcp.upbound.io/v1beta1
kind: RecordSet
metadata:
  name: example
spec:
  forProvider:
    # Note the trailing period
    name: test.example-281496.com.
    managedZone: example
    rrdatas:
    - 8.8.8.8
    ttl: 300
    type: A
