apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: OAuthIdPConfig
metadata:
  labels:
    testing.upbound.io/example-name: oauth_idp_config
  name: oauth-idp-config
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    displayName: Display Name
    enabled: true
    issuer: issuer
    name: oidc.oauth-idp-config

---

