apiVersion: identityplatform.gcp.upbound.io/v1alpha1
kind: OAuthIdPConfig
metadata:
  name: example
spec:
  forProvider:
    clientId: client-id
    clientSecret: secret
    displayName: Display Name
    enabled: true
    issuer: issuer
    name: oidc.oauth-idp-config
  providerConfigRef:
    name: example
