apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: TenantDefaultSupportedIdPConfig
metadata:
  labels:
    testing.upbound.io/example-name: idp_config
  name: idp-config
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    enabled: true
    idpId: playgames.google.com
    tenantSelector:
      matchLabels:
        testing.upbound.io/example-name: tenant

---

apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant
  name: tenant
spec:
  forProvider:
    displayName: tenant

---

