apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant
  name: tenant
spec:
  forProvider:
    allowPasswordSignup: true
    displayName: tenant

---

