apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: TenantOAuthIdPConfig
metadata:
  labels:
    testing.upbound.io/example-name: tenant_oauth_idp_config
  name: tenant-oauth-idp-config
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    displayName: Display Name
    enabled: true
    issuer: issuer
    name: oidc.oauth-idp-config
    tenantSelector:
      matchLabels:
        testing.upbound.io/example-name: tenant

---

apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant
  name: tenant
spec:
  forProvider:
    displayName: tenant

---

