apiVersion: tags.gcp.upbound.io/v1alpha1
kind: TagKey
metadata:
  name: example
spec:
  forProvider:
    description: For keyname resources.
    parent: organizations/123456789
    shortName: keyname
  providerConfigRef:
    name: example
