apiVersion: bigquery.gcp.upbound.io/v1alpha1
kind: Connection
metadata:
  name: example
spec:
  forProvider:
    cloudSql:
    - credential:
      - passwordSecretRef:
          key: attribute.password
          name: example-sql-user
          namespace: crossplane-system
        username: ${google_sql_user.user.name}
      database: ${google_sql_database.db.name}
      instanceId: ${google_sql_database_instance.instance.connection_name}
      type: POSTGRES
    description: a riveting description
    friendlyName: "\U0001F44B"
  providerConfigRef:
    name: example
