apiVersion: apikeys.gcp.upbound.io/v1alpha1
kind: Key
metadata:
  name: example
spec:
  forProvider:
    displayName: sample-key
    name: key
    project: ${google_project.basic.name}
    restrictions:
    - androidKeyRestrictions:
      - allowedApplications:
        - packageName: com.example.app123
          sha1Fingerprint: 1699466a142d4682a5f91b50fdf400f2358e2b0b
      apiTargets:
      - methods:
        - GET*
        service: translate.googleapis.com
  providerConfigRef:
    name: example
