apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Reservation
metadata:
  annotations:
    meta.upbound.io/example-id: bigquery/v1beta1/reservation
  labels:
    testing.upbound.io/example-name: reservation
  name: reservation
spec:
  forProvider:
    ignoreIdleSlots: false
    location: asia-northeast1
    slotCapacity: 0

---

