apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: TableIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: bigquery/v1beta1/tableiampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    datasetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    policyData: ${data.google_iam_policy.admin.policy_data}
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    tableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

