apiVersion: container.gcp.upbound.io/v1alpha1
kind: AwsNodePool
metadata:
  name: example
spec:
  forProvider:
    annotations:
      label-one: value-one
    autoscaling:
    - maxNodeCount: 5
      minNodeCount: 1
    cluster: name
    config:
    - configEncryption:
      - kmsKeyArn: arn:aws:kms:my-aws-region:012345678910:key/12345678-1234-1234-1234-123456789111
      iamInstanceProfile: my--1p-dev-nodepool
      instanceType: t3.medium
      labels:
        label-one: value-one
      proxyConfig:
      - secretArn: arn:aws:secretsmanager:us-west-2:126285863215:secret:proxy_config20210824150329476300000001-ABCDEF
        secretVersion: 12345678-ABCD-EFGH-IJKL-987654321098
      rootVolume:
      - iops: 3000
        kmsKeyArn: arn:aws:kms:my-aws-region:012345678910:key/12345678-1234-1234-1234-123456789111
        sizeGib: 10
        volumeType: GP3
      securityGroupIds:
      - sg-00000000000000000
      sshConfig:
      - ec2KeyPair: my--1p-dev-ssh
      tags:
        tag-one: value-one
      taints:
      - effect: PREFER_NO_SCHEDULE
        key: taint-key
        value: taint-value
    location: us-west1
    maxPodsConstraint:
    - maxPodsPerNode: 110
    name: node-pool-name
    project: my-project-name
    subnetId: subnet-00000000000000000
    version: ${data.google_container_aws_versions.versions.valid_versions[0]}
  providerConfigRef:
    name: example
