apiVersion: container.gcp.upbound.io/v1alpha2
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    initialNodeCount: 1
    location: us-central1
    removeDefaultNodePool: true
  providerConfigRef:
    name: example
