apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  labels:
    testing.upbound.io/example-name: secret-version-basic
  name: secret-version-basic
spec:
  forProvider:
    secretDataSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretSelector:
      matchLabels:
        testing.upbound.io/example-name: secret-basic

---

apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: secret-basic
  name: secret-basic
spec:
  forProvider:
    labels:
      label: my-label
    replication:
    - automatic: true
    secretId: secret-version

---

