apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: secret-basic
  name: secret-basic
spec:
  forProvider:
    labels:
      label: my-label
    replication:
    - userManaged:
      - replicas:
        - location: us-central1
        - location: us-east1
    secretId: secret

---

