apiVersion: secretmanager.gcp.upbound.io/v1alpha1
kind: SecretVersion
metadata:
  name: example
spec:
  forProvider:
    secret: ${google_secret_manager_secret.secret-basic.id}
    secretDataSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
  providerConfigRef:
    name: example
