apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  labels:
    testing.upbound.io/example-name: example_instance
  # ${Rand...} is not valid YAML and is used with automated testing
  name: example-instance-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    region: "us-central1"
    databaseVersion: "MYSQL_5_7"
    settings:
      - tier: "db-f1-micro"
        diskSize: 20
    deletionProtection: false   # allow crossplane to delete the instance automatically
  writeConnectionSecretToRef:
    name: example-sql-db-instance-secret
    namespace: upbound-system
