apiVersion: sql.gcp.upbound.io/v1beta1
kind: SSLCert
metadata:
  labels:
    testing.upbound.io/example-name: example_cert
  name: example-cert
spec:
  forProvider:
    commonName: client-name
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example_instance
  writeConnectionSecretToRef:
    name: example-sql-ssl-secret
    namespace: upbound-system

