apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_user
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: example-sql-user
      namespace: upbound-system
      key: password
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example_instance

---

apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_user
  name: example-sql-user
  namespace: upbound-system
