apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: example-sql-user
  namespace: upbound-system
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: example-sql-user
      namespace: upbound-system
      key: password
    instanceRef:
      name: example-instance
