apiVersion: healthcare.gcp.upbound.io/v1beta1
kind: Dataset
metadata:
  annotations:
    meta.upbound.io/example-id: healthcare/v1beta1/dataset
  labels:
    testing.upbound.io/example-name: dataset
  name: dataset
spec:
  forProvider:
    name: dataset
    location: us-central1
    timeZone: UTC
