apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: bucket-object
  name: bucket-object
spec:
  forProvider:
    bucketSelector: 
      matchLabels:
        testing.upbound.io/example-name: bucket-object
    name: bucket-object
    content: "Upbound!"
    contentType: text/plain

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: bucket-object
  name: bucket-object-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
