apiVersion: storage.gcp.upbound.io/v1beta1
kind: DefaultObjectACL
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/defaultobjectacl
  labels:
    testing.upbound.io/example-name: default-object-acl
  name: default-object-acl
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default-object-acl
    roleEntity:
    - READER:allAuthenticatedUsers

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/defaultobjectacl
  labels:
    testing.upbound.io/example-name: default-object-acl
  name: default-object-acl-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: US
