apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: TenantDefaultSupportedIdPConfig
metadata:
  labels:
    testing.upbound.io/example-name: tenant-default-supported-idp-config
  name: tenant-default-supported-idp-config
spec:
  forProvider:
    clientIdSecretRef:
      key: clientId
      name: tenant-default-supported-idp-config
      namespace: upbound-system
    clientSecretSecretRef:
      key: clientSecret
      name: tenant-default-supported-idp-config
      namespace: upbound-system
    enabled: true
    idpId: google.com
    tenantSelector:
      matchLabels:
        testing.upbound.io/example-name: tenant-default-supported-idp-config
---

apiVersion: v1
data:
  clientId: dXBib3VuZA==
  clientSecret: MTIzNDU=
kind: Secret
metadata:
  name: tenant-default-supported-idp-config
  namespace: upbound-system

---

apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant-default-supported-idp-config
  name: tenant-default-supported-idp-config
spec:
  forProvider:
    # displayName should start with a letter and only consist of letters, digits and hyphens with 4-20 characters
    displayName: tenant-default
