apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: TenantInboundSAMLConfig
metadata:
  labels:
    testing.upbound.io/example-name: tenant-inbound-saml-config
  name: tenant-inbound-saml-config
spec:
  forProvider:
    name: saml.inbound-saml-config
    displayName: Display Name
    idpConfig:
    - idpCertificates:
      - x509CertificateSecretRef:
          key: rsa_cert.pem
          name: tenant-inbound-saml-config
          namespace: upbound-system
      idpEntityId: tf-idp
      signRequest: true
      ssoUrl: https://example.com
    spConfig:
    - callbackUri: https://example.com
      spEntityId: tf-sp
    tenantSelector:
      matchLabels:
        testing.upbound.io/example-name: tenant-inbound-saml-config

---

apiVersion: v1
data:
  rsa_cert.pem: dXBib3VuZA==
kind: Secret
metadata:
  name: tenant-inbound-saml-config
  namespace: upbound-system

---

apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant-inbound-saml-config
  name: tenant-inbound-saml-config
spec:
  forProvider:
    # displayName should start with a letter and only consist of letters, digits and hyphens with 4-20 characters
    displayName: tenant-inbound
