apiVersion: identityplatform.gcp.upbound.io/v1beta1
kind: Tenant
metadata:
  labels:
    testing.upbound.io/example-name: tenant
  name: tenant
spec:
  forProvider:
    allowPasswordSignup: true
    # displayName should start with a letter and only consist of letters, digits and hyphens with 4-20 characters
    displayName: tenant
