apiVersion: servicenetworking.gcp.upbound.io/v1beta1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: servicenetworking/v1beta1/connection
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: peering_network
    reservedPeeringRangesRefs:
    - name: private_ip_alloc
    service: servicenetworking.googleapis.com

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  annotations:
    meta.upbound.io/example-id: servicenetworking/v1beta1/connection
  labels:
    testing.upbound.io/example-name: private_ip_alloc
  name: private-ip-alloc
spec:
  forProvider:
    addressType: INTERNAL
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: peering_network
    prefixLength: 16
    purpose: VPC_PEERING

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: servicenetworking/v1beta1/connection
  labels:
    testing.upbound.io/example-name: peering_network
  name: peering-network
spec:
  forProvider: {}

---

