apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    healthChecks:
    - ${google_compute_http_health_check.default.id}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HTTPHealthCheck
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    checkIntervalSec: 1
    requestPath: /
    timeoutSec: 1

---

