apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  labels:
    testing.upbound.io/example-name: image_backend
  name: image-backend
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: image_bucket
    description: Contains beautiful images
    enableCdn: true

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: image_bucket
  name: image-bucket
spec:
  forProvider:
    location: EU

---

