apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucketSignedURLKey
metadata:
  name: example
spec:
  forProvider:
    backendBucketRef:
      name: example
    keyValueSecretRef:
      key: attribute.b64_url
      name: example-id
      namespace: crossplane-system
    name: test-key
