apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalNetworkEndpointGroup
metadata:
  labels:
    testing.upbound.io/example-name: neg
  name: neg
spec:
  forProvider:
    defaultPort: "90"
    networkEndpointType: INTERNET_FQDN_PORT

---

