apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalNetworkEndpoint
metadata:
  labels:
    testing.upbound.io/example-name: default-endpoint
  name: default-endpoint
spec:
  forProvider:
    fqdn: www.example.com
    globalNetworkEndpointGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: neg
    port: 90

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalNetworkEndpointGroup
metadata:
  labels:
    testing.upbound.io/example-name: neg
  name: neg
spec:
  forProvider:
    defaultPort: "90"
    networkEndpointType: INTERNET_FQDN_PORT

---

