apiVersion: compute.gcp.upbound.io/v1beta1
kind: HaVPNGateway
metadata:
  labels:
    testing.upbound.io/example-name: ha_gateway1
  name: ha-gateway1
spec:
  forProvider:
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: network1
    region: us-central1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: network1
  name: network1
spec:
  forProvider:
    autoCreateSubnetworks: false

---

