apiVersion: compute.gcp.upbound.io/v1beta1
kind: ImageIAMPolicy
metadata:
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    image: ${google_compute_image.example.name}
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: ${google_compute_image.example.project}

---

