apiVersion: compute.gcp.upbound.io/v1beta1
kind: ImageIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/imageiampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: ${google_compute_image.example.project}

---

