apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bootDisk:
    - initializeParams:
      - image: debian-cloud/debian-9
    machineType: e2-medium
    metadata:
      foo: bar
    metadataStartupScript: echo hi > /test.txt
    networkInterface:
    - accessConfig:
      - {}
      networkSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    scratchDisk:
    - interface: SCSI
    serviceAccount:
    - email: ${google_service_account.default.email}
      scopes:
      - cloud-platform
    tags:
    - foo
    - bar
    zone: us-central1-a

---

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    displayName: Service Account

---

