apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceFromTemplate
metadata:
  name: example
spec:
  forProvider:
    canIpForward: false
    labels:
      my_key: my_value
    name: instance-from-template
    sourceInstanceTemplateRef:
      name: example
    zone: us-central1-a
