apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceGroup
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Terraform test instance group
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    zone: us-central1-a

---

