apiVersion: compute.gcp.upbound.io/v1beta1
kind: InterconnectAttachment
metadata:
  labels:
    testing.upbound.io/example-name: on_prem
  name: on-prem
spec:
  forProvider:
    edgeAvailabilityDomain: AVAILABILITY_DOMAIN_1
    mtu: 1500
    routerSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar
    type: PARTNER

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    autoCreateSubnetworks: false

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    bgp:
    - asn: 16550
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

