apiVersion: compute.gcp.upbound.io/v1beta1
kind: ManagedSSLCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    managed:
    - domains:
      - sslcert.tf-test.club.

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    healthChecksRefs:
    - name: default
    portName: http
    protocol: HTTP
    timeoutSec: 10

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalForwardingRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    portRange: 443
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HTTPHealthCheck
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    checkIntervalSec: 1
    requestPath: /
    timeoutSec: 1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetHTTPSProxy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    sslCertificatesRefs:
    - name: default
    urlMapSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: URLMap
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    defaultServiceSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    description: a description
    hostRule:
    - hosts:
      - sslcert.tf-test.club
      pathMatcher: allpaths
    pathMatcher:
    - defaultServiceSelector:
        matchLabels:
          testing.upbound.io/example-name: default
      name: allpaths
      pathRule:
      - paths:
        - /*
        serviceSelector:
          matchLabels:
            testing.upbound.io/example-name: default

---

apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZone
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: zone
  name: zone
spec:
  forProvider:
    dnsName: sslcert.tf-test.club.

---

apiVersion: dns.gcp.upbound.io/v1beta1
kind: RecordSet
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: set
  name: set
spec:
  forProvider:
    managedZoneSelector:
      matchLabels:
        testing.upbound.io/example-name: zone
    name: sslcert.tf-test.club.
    rrdatas:
    - ${google_compute_global_forwarding_rule.default.ip_address}
    ttl: 3600
    type: A

---

