apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkEndpoint
metadata:
  name: example
spec:
  forProvider:
    instance: ${google_compute_instance.endpoint-instance.name}
    ipAddress: ${google_compute_instance.endpoint-instance.network_interface[0].network_ip}
    networkEndpointGroup: ${google_compute_network_endpoint_group.neg.name}
    port: ${google_compute_network_endpoint_group.neg.default_port}
