apiVersion: compute.gcp.upbound.io/v1beta1
kind: ProjectDefaultNetworkTier
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    networkTier: PREMIUM

---

