apiVersion: compute.gcp.upbound.io/v1alpha1
kind: ProjectMetadata
metadata:
  name: example
spec:
  forProvider:
    metadata:
      "13": "42"
      fizz: buzz
      foo: bar
  providerConfigRef:
    name: example
