apiVersion: compute.gcp.upbound.io/v1beta1
kind: ProjectMetadata
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    metadata:
      "13": "42"
      fizz: buzz
      foo: bar

---

