apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionSSLCertificate
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificateSecretRef:
      key: attribute.certificate.crt
      name: example-secret
      namespace: upbound-system
    description: a description
    privateKeySecretRef:
      key: attribute.private.key
      name: example-secret
      namespace: upbound-system
    region: us-central1

---

