apiVersion: compute.gcp.upbound.io/v1beta1
kind: ResourcePolicy
metadata:
  name: example
spec:
  forProvider:
    region: us-central1
    snapshotSchedulePolicy:
    - schedule:
      - dailySchedule:
        - daysInCycle: 1
          startTime: "04:00"
