apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterInterface
metadata:
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    ipRange: 169.254.1.1/30
    name: interface-1
    region: us-central1
    router: router-1
    vpnTunnel: tunnel-1

---

