apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  name: example
spec:
  forProvider:
    ipCidrRange: 10.2.0.0/16
    networkRef:
      name: example
    region: us-central1
    secondaryIpRange:
    - ipCidrRange: 192.168.10.0/24
      rangeName: tf-test-secondary-range-update1
