apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetPool
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    healthChecksRefs:
    - name: default
    instances:
    - us-central1-a/myinstance1
    - us-central1-b/myinstance2

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HTTPHealthCheck
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    checkIntervalSec: 1
    requestPath: /
    timeoutSec: 1

---

