apiVersion: notebooks.gcp.upbound.io/v1beta1
kind: Runtime
metadata:
  annotations:
    meta.upbound.io/example-id: notebooks/v1beta1/runtime
  labels:
    testing.upbound.io/example-name: runtime
  name: runtime
spec:
  forProvider:
    accessConfig:
    - accessType: SERVICE_ACCOUNT
      runtimeOwner: "${data.google_iam_member.op-user}"
    location: us-central1
    virtualMachine:
    - virtualMachineConfig:
      - dataDisk:
        - initializeParams:
          - diskSizeGb: 100
            diskType: PD_STANDARD
        machineType: n1-standard-4
    softwareConfig:
      - enableHealthMonitoring: true
