apiVersion: iap.gcp.upbound.io/v1alpha1
kind: AppEngineServiceIAMPolicy
metadata:
  name: example
spec:
  forProvider:
    appId: ${google_app_engine_standard_app_version.version.project}
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: ${google_app_engine_standard_app_version.version.project}
    service: myapp
  providerConfigRef:
    name: example
