apiVersion: filestore.gcp.upbound.io/v1alpha1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    fileShares:
    - capacityGb: 2660
      name: share1
    location: us-central1-b
    name: test-instance
    networks:
    - modes:
      - MODE_IPV4
      network: default
    tier: PREMIUM
  providerConfigRef:
    name: example
