apiVersion: kms.gcp.upbound.io/v1beta1
kind: KeyRingIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/keyringiammember
  labels:
    testing.upbound.io/example-name: keyring-iam-member
  name: keyring-iam-member
spec:
  forProvider:
    member: "${data.google_iam_member.member}"
    role: "roles/editor"
    keyRingIdSelector:
      matchLabels:
        testing.upbound.io/example-name: keyring-iam-member

---

apiVersion: kms.gcp.upbound.io/v1beta1
kind: KeyRing
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/keyringiammember
  labels:
    testing.upbound.io/example-name: keyring-iam-member
  name: keyring-iam-member-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: global
