apiVersion: kms.gcp.upbound.io/v1beta1
kind: SecretCiphertext
metadata:
  labels:
    testing.upbound.io/example-name: my_password
  name: my-password
spec:
  forProvider:
    cryptoKeySelector:
      matchLabels:
        testing.upbound.io/example-name: cryptokey
    plaintextSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: kms.gcp.upbound.io/v1beta1
kind: CryptoKey
metadata:
  labels:
    testing.upbound.io/example-name: cryptokey
  name: cryptokey
spec:
  forProvider:
    keyRingSelector:
      matchLabels:
        testing.upbound.io/example-name: keyring
    rotationPeriod: 100000s

---

apiVersion: kms.gcp.upbound.io/v1beta1
kind: KeyRing
metadata:
  labels:
    testing.upbound.io/example-name: keyring
  name: keyring
spec:
  forProvider:
    location: global

---

