apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretiammember
  labels:
    testing.upbound.io/example-name: secret-iam-member
  name: secret-iam-member
spec:
  forProvider:
    member: "${data.google_iam_member.member}"
    role: "roles/viewer"
    secretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: secret-iam-member

---

apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretiammember
  labels:
    testing.upbound.io/example-name: secret-iam-member
  name: secret-iam-member
spec:
  forProvider:
    labels:
      environment: dev
    replication:
    - userManaged:
      - replicas:
        - location: us-west2
    secretId: secret-iam-member
