apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secret
  labels:
    testing.upbound.io/example-name: secret
  name: secret
spec:
  forProvider:
    labels:
      environment: dev
    replication:
    - userManaged:
      - replicas:
        - location: us-west2
