apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: example
spec:
  forProvider:
    secretDataSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
    secretRef:
      name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: crossplane-system
type: Opaque
stringData:
  example-key: "Super Important Secret"