apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: example
spec:
  forProvider:
    labels:
      label: my-label
    replication:
    - userManaged:
      - replicas:
        - location: us-west2
    secretId: secret
