apiVersion: redis.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    tier: STANDARD_HA
    region: us-west2
    memorySizeGb: 1
    labels:
      owner: instanceowner
    authEnabled: true
  writeConnectionSecretToRef:
    name: example-redis-connection-details
    namespace: upbound-system
