apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: LiteSubscription
metadata:
  name: example
spec:
  forProvider:
    deliveryConfig:
    - deliveryRequirement: DELIVER_AFTER_STORED
    topicRef:
      name: example
