apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: LiteTopic
metadata:
  name: example
spec:
  forProvider:
    partitionConfig:
    - capacity:
      - publishMibPerSec: 4
        subscribeMibPerSec: 8
      count: 1
    project: ${data.google_project.project.number}
    reservationConfig:
    - throughputReservationRef:
        name: example
    retentionConfig:
    - perPartitionBytes: 32212254720
