apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: LiteTopic
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    partitionConfig:
    - capacity:
      - publishMibPerSec: 4
        subscribeMibPerSec: 8
      count: 1
    project: ${data.google_project.project.number}
    reservationConfig:
    - throughputReservationSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    retentionConfig:
    - perPartitionBytes: 32212254720

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: LiteReservation
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    project: ${data.google_project.project.number}
    throughputCapacity: 2

---

