apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Subscription
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ackDeadlineSeconds: 20
    labels:
      foo: bar
    pushConfig:
    - attributes:
        x-goog-version: v1
      pushEndpoint: https://example.com/push
    topicSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider: {}

---

