apiVersion: pubsub.gcp.upbound.io/v1alpha1
kind: Topic
metadata:
  name: example
spec:
  forProvider:
    labels:
      foo: bar
    messageRetentionDuration: 86600s
    name: example-topic
  providerConfigRef:
    name: example
