apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: pubsub/v1beta1/topic
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}
