apiVersion: bigtable.gcp.upbound.io/v1alpha1
kind: InstanceIAMPolicy
metadata:
  name: example
spec:
  forProvider:
    instance: your-bigtable-instance
    policyData: ${data.google_iam_policy.admin.policy_data}
    project: your-project
  providerConfigRef:
    name: example
