apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: example-gke-cluster
spec:
  forProvider:
    initialNodeCount: 1
    location: us-central1
    removeDefaultNodePool: false
  writeConnectionSecretToRef:
    name: example-gke-cluster-secret
    namespace: upbound-system
