apiVersion: composer.gcp.upbound.io/v1beta1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: composer/v1beta1/environment
  labels:
    testing.upbound.io/example-name: composer-environment
  name: composer-environment
spec:
  forProvider:
    region: us-central1
    config:
      - nodeConfig:
        - ipAllocationPolicy:
            - useIpAliases: true
              clusterIpv4CidrBlock: 10.80.0.0/14
              servicesIpv4CidrBlock: 10.84.0.0/20
