apiVersion: kms.gcp.upbound.io/v1beta1
kind: CryptoKey
metadata:
  labels:
    testing.upbound.io/example-name: example-key
  name: example-key
spec:
  forProvider:
    keyRingSelector:
      matchLabels:
        testing.upbound.io/example-name: keyring
    rotationPeriod: 100000s

---

apiVersion: kms.gcp.upbound.io/v1beta1
kind: KeyRing
metadata:
  labels:
    testing.upbound.io/example-name: keyring
  name: keyring
spec:
  forProvider:
    location: global

---

