apiVersion: dialogflow.gcp.upbound.io/v1alpha1
kind: EntityType
metadata:
  name: example
spec:
  forProvider:
    displayName: ""
    entities:
    - synonyms:
      - synonym1
      - synonym2
      value: value1
    - synonyms:
      - synonym3
      - synonym4
      value: value2
    kind: KIND_MAP
  providerConfigRef:
    name: example
