apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalNetworkEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalnetworkendpoint
  labels:
    testing.upbound.io/example-name: global-network-endpoint
  name: global-network-endpoint
spec:
  forProvider:
    fqdn: www.example.com
    globalNetworkEndpointGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: global-network-endpoint
    port: 90

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalNetworkEndpointGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalnetworkendpoint
  labels:
    testing.upbound.io/example-name: global-network-endpoint
  name: global-network-endpoint
spec:
  forProvider:
    defaultPort: 90
    networkEndpointType: INTERNET_FQDN_PORT
