apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: ReservationAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: bigquery/v1beta1/reservationassignment
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    assignee: projects/zippy-parity-368910
    jobType: PIPELINE
    reservationSelector:
      matchLabels:
        testing.upbound.io/example-name: reservation

---

apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Reservation
metadata:
  annotations:
    meta.upbound.io/example-id: bigquery/v1beta1/reservationassignment
  labels:
    testing.upbound.io/example-name: reservation
  name: reservation
spec:
  forProvider:
    ignoreIdleSlots: false
    location: us-central1
    slotCapacity: 0
