apiVersion: firebaserules.gcp.upbound.io/v1alpha1
kind: Ruleset
metadata:
  name: example
spec:
  forProvider:
    project: my-project-name
    source:
    - files:
      - content: 'service cloud.firestore {match /databases/{database}/documents {
          match /{document=**} { allow read, write: if false; } } }'
        fingerprint: ""
        name: firestore.rules
      language: ""
  providerConfigRef:
    name: example
