apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: bucket
  labels:
     testing.upbound.io/example-name: upbound-example-990150596479
  annotations:
    # Note that the external-name will be the actual bucket name, so it has to be globally
    #  unique/available.
    crossplane.io/external-name: upbound-example-990150596479
spec:
  forProvider:
    cors:
    - maxAgeSeconds: 3600
      method:
      - GET
      - HEAD
      - PUT
      - POST
      - DELETE
      origin:
      - http://image-store.com
      responseHeader:
      - '*'
    forceDestroy: true
    location: EU
    uniformBucketLevelAccess: true
    website:
    - mainPageSuffix: index.html
      notFoundPage: 404.html
