apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketacl
    upjet.upbound.io/manual-intervention: " Doesn't work in automated for an unknown reason."
  labels:
    testing.upbound.io/example-name: image-store-acl
  name: image-store-acl
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: image-store
    roleEntity:
    - READER:allAuthenticatedUsers

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/bucketacl
  labels:
    testing.upbound.io/example-name: image-store
  name: image-store-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: EU

