apiVersion: logging.gcp.upbound.io/v1beta1
kind: LogView
metadata:
  annotations:
    meta.upbound.io/example-id: logging/v1beta1/logview
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: basic
    description: A logging view configured with Terraform
    filter: SOURCE("projects/myproject") AND resource.type = "gce_instance" AND LOG_ID("stdout")

---

apiVersion: logging.gcp.upbound.io/v1beta1
kind: ProjectBucketConfig
metadata:
  annotations:
    meta.upbound.io/example-id: logging/v1beta1/logview
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    bucketId: _Default
    location: global
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    retentionDays: 30

---

