apiVersion: monitoring.gcp.upbound.io/v1beta1
kind: AlertPolicy
metadata:
  labels:
    testing.upbound.io/example-name: example_alert_policy
  name: example-alert-policy
spec:
  forProvider:
    combiner: OR
    conditions:
      - conditionThreshold:
          - aggregations:
              - alignmentPeriod: 60s
                perSeriesAligner: ALIGN_RATE
            comparison: COMPARISON_GT
            duration: 60s
            filter: metric.type="compute.googleapis.com/instance/disk/write_bytes_count"
              AND resource.type="gce_instance"
        displayName: test condition
    displayName: My Alert Policy
    userLabels:
      foo: bar
