apiVersion: spanner.gcp.upbound.io/v1alpha1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    config: regional-us-central1
    displayName: Test Spanner Instance
    labels:
      foo: bar
    numNodes: 2
  providerConfigRef:
    name: example
