apiVersion: healthcare.gcp.upbound.io/v1alpha1
kind: HL7V2StoreIAMPolicy
metadata:
  name: example
spec:
  forProvider:
    hl7V2StoreId: your-hl7-v2-store-id
    policyData: ${data.google_iam_policy.admin.policy_data}
  providerConfigRef:
    name: example
