apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: OrganizationIAMMember
metadata:
  labels:
    testing.upbound.io/example-name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires organization IAM permissions"
  name: example
spec:
  forProvider:
    orgId: "123456789"
    member: "user:jane@example.com"
    role: "roles/viewer"
