apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: OrganizationIAMBinding
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires orginazational IAM permissions"
spec:
  forProvider:
    orgId: "123456789"
    members:
      - "user:jane@example.com"
    role: "roles/viewer"
