apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: OrganizationIAMAuditConfig
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires orginazational IAM permissions"
spec:
  forProvider:
    orgId: "123456789"
    service: allServices
    auditLogConfig:
      - logType: DATA_READ
        exemptedMembers:
          - "user:joebloggs@hashicorp.com"
