apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectService
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Project level resource and is environment specific"
spec:
  forProvider:
    disableDependentServices: false
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    service: clouddeploy.googleapis.com
