apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectDefaultServiceAccounts
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: example
  annotations:
    upjet.upbound.io/manual-intervention: "This is a project level resource and could be distructive"
spec:
  forProvider:
    action: DEPRIVILEGE
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
