apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMPolicy
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Members are dependent on the project and leak sensitive information"
spec:
  forProvider:
    policyData: |
      {
        "bindings": [
          {
            "members": [
              "user:jane@example.com"
            ],
            "role": "roles/viewer"
          }
        ]
      }
    projectRef:
      name: example
