apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectUsageExportBucket
metadata:
  name: example
spec:
  forProvider:
    bucketRef: 
      name: example-usage-tracking-bucket
    projectRef:
      name: example
