apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  labels:
    testing.upbound.io/example-name: example_service_account_key
  name: example-service-account-key
spec:
  forProvider:
    publicKeyType: TYPE_X509_PEM_FILE
    serviceAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_service_account_key
  writeConnectionSecretToRef:
    name: example-service-account-key-secret
    namespace: upbound-system
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/example-name: example_service_account_key
  name: example-service-account-key
spec:
  forProvider:
    displayName: Used for example service account key testing


