apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    testing.upbound.io/example-name: example_service_account
  name: example-service-account
spec:
  forProvider:
    displayName: Upbound Example Service Account
