apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceNetworkingPeeredDNSDomain
metadata:
  name: example
spec:
  forProvider:
    dnsSuffix: example.com.
    network: service-peered-network
    service: servicenetworking.googleapis.com

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: service-peered-network
  name: service-peered-network
spec:
  forProvider:
    autoCreateSubnetworks: false
