apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceNetworkingPeeredDNSDomain
metadata:
  labels:
    testing.upbound.io/example-name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires a network in a consumer project"
  name: example
spec:
  forProvider:
    dnsSuffix: example.com.
    network: consumer-network
    service: servicenetworking.googleapis.com
