apiVersion: storage.gcp.upbound.io/v1alpha2
kind: Bucket
metadata:
  name: official-example-bucket
  annotations:
    # Note that this will be the actual bucket name, so it has to be globally
    #  unique/available.
    crossplane.io/external-name: official-example-bucket
spec:
  forProvider:
    cors:
    - maxAgeSeconds: 3600
      method:
      - GET
      - HEAD
      - PUT
      - POST
      - DELETE
      origin:
      - http://image-store.com
      responseHeader:
      - '*'
    forceDestroy: true
    location: EU
    uniformBucketLevelAccess: true
    website:
    - mainPageSuffix: index.html
      notFoundPage: 404.html
  providerConfigRef:
    name: example
