apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketAccessControl
metadata:
  labels:
    testing.upbound.io/example-name: public_rule
  name: public-rule
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    entity: allUsers
    role: READER

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    location: US

---

