apiVersion: dataproc.gcp.upbound.io/v1beta1
kind: AutoscalingPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: dataproc/v1beta1/autoscalingpolicy
  labels:
    testing.upbound.io/example-name: asp
  name: asp
spec:
  forProvider:
    basicAlgorithm:
    - yarnConfig:
      - gracefulDecommissionTimeout: 30s
        scaleDownFactor: 0.5
        scaleUpFactor: 0.5
    location: us-central1
    workerConfig:
    - maxInstances: 3