apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: dnspolicies.provider.upbound.io
spec:
  claimNames:
    kind: DnsPolicyClaim
    plural: dnspolicyclaims
  group: provider.upbound.io
  names:
    kind: DnsPolicy
    plural: dnspolicies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
