apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: DomainMapping
metadata:
  labels:
    testing.upbound.io/example-name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Caller must be authorized to administer the domain example.com"
  name: example 
spec:
  forProvider:
    name: example.com
    location: us-central1
    metadata:
    - namespaceSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    spec:
    - routeNameSelector:
        matchLabels:
          testing.upbound.io/example-name: example
