apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composite.pubsubs.provider.upbound.io
  labels:
    cloud: gcp
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: provider.upbound.io/v1alpha1
    kind: PubSub
  patchSets:
    - name: matchClaimName
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.metadata.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
    - base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: Topic
        spec:
          forProvider: {}            
      patches:
        - type: PatchSet
          patchSetName: matchClaimName
        - fromFieldPath: "metadata.name"
          toFieldPath: "status.topicName"
          type: ToCompositeFieldPath
    - base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: TopicIAMPolicy
        spec:
          forProvider:
            policyData: |
              {
                "bindings": [
                  {
                    "members": [
                      "user:jane@example.com"
                    ],
                    "role": "roles/viewer"
                  }
                ]
              }
            topicSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: matchClaimName
    - base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: Subscription
        spec:
          forProvider:
            topicSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: matchClaimName
    - base:
        apiVersion: pubsub.gcp.upbound.io/v1beta1
        kind: SubscriptionIAMPolicy
        spec:
          forProvider:
            policyData: |
              {
                "bindings": [
                  {
                    "members": [
                      "user:jane@example.com"
                    ],
                    "role": "roles/viewer"
                  }
                ]
              }
            subscriptionSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: matchClaimName