apiVersion: orgpolicy.gcp.upbound.io/v1alpha1
kind: Policy
metadata:
  name: example
spec:
  forProvider:
    name: projects/${google_project.basic.name}/policies/iam.disableServiceAccountKeyUpload
    parent: projects/${google_project.basic.name}
    spec:
    - rules:
      - enforce: "FALSE"
  providerConfigRef:
    name: example
