apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/projectiammember
  labels:
    testing.upbound.io/example-name: project-iam-member
  name: project-iam-member
spec:
  forProvider:
    member: "${data.google_iam_member.member}"
    role: "roles/viewer"
    project: ${data.cloudplatform_project.projectId}
