apiVersion: sql.gcp.upbound.io/v1alpha2
kind: DatabaseInstance
metadata:
  name: example
spec:
  forProvider:
    databaseVersion: POSTGRES_11
    region: us-central1
    settings:
    - tier: db-f1-micro
  providerConfigRef:
    name: example
