apiVersion: sql.gcp.upbound.io/v1alpha2
kind: User
metadata:
  name: example
spec:
  forProvider:
    host: me.com
    instanceRef:
      name: example
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
  providerConfigRef:
    name: example
