apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example-attached
spec:
  forProvider:
    image: debian-11-bullseye-v20220719
    physicalBlockSizeBytes: 4096
    type: pd-ssd
    zone: us-central1-a

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example-attached-instance
spec:
  forProvider:
    machineType: e2-medium
    zone: us-central1-a
    networkInterface:
      - network: default
    bootDisk:
      - initializeParams:
          - image: debian-cloud/debian-11

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: AttachedDisk
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example-attached
spec:
  forProvider:
    zone: us-central1-a
    diskSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example

