apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceTemplate
metadata:
  name: example-autoscaler
spec:
  forProvider:
    canIpForward: false
    description: This template is used to create app server instances.
    disk:
      - autoDelete: false
        boot: true
        sourceImage: debian-cloud/debian-11
    instanceDescription: Description assigned to instances
    machineType: e2-medium
    networkInterface:
      - network: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HTTPHealthCheck
metadata:
  name: example-autoscaler
spec:
  forProvider:
    checkIntervalSec: 1
    requestPath: /health_check
    timeoutSec: 1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HealthCheck
metadata:
  name: example-autoscaler
spec:
  forProvider:
    checkIntervalSec: 1
    tcpHealthCheck:
      - port: 80
    timeoutSec: 1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetPool
metadata:
  name: example-autoscaler
spec:
  forProvider:
    region: us-central1
    healthChecksRefs:
      - name: example-autoscaler
    instances:
    - us-central1-a/example-autoscaler

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceGroupManager
metadata:
  name: example-autoscaler
spec:
  forProvider:
    autoHealingPolicies:
    - healthCheckRef:
        name: example-autoscaler
      initialDelaySec: 300
    baseInstanceName: app
    namedPort:
    - name: custom
      port: 8888
    targetPoolsRefs:
    - name: example-autoscaler
    targetSize: 2
    version:
    - instanceTemplateRef:
        name: example-autoscaler
    zone: us-central1-a

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Autoscaler
metadata:
  name: example
spec:
  forProvider:
    autoscalingPolicy:
    - cooldownPeriod: 60
      maxReplicas: 5
      minReplicas: 1
    # InstanceGroupManager
    targetRef:
      name: example-autoscaler
    zone: us-central1-a
