apiVersion: compute.gcp.upbound.io/v1beta1
kind: HealthCheck
metadata:
  name: example-backend-service
spec:
  forProvider:
    checkIntervalSec: 1
    httpHealthCheck:
      - port: 80
    timeoutSec: 1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "HealthCheck URL is enviroment specific"
spec:
  forProvider:
    healthChecks:
    - https://www.googleapis.com/compute/v1/projects/default/global/healthChecks/example-backend-service
