apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: example-backend-key
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  name: example-backend-key
spec:
  forProvider:
    bucketNameRef:
      name: example-backend-key
    description: Contains beautiful images
    enableCdn: true

---

apiVersion: v1
data:
  attribute.b64_url: WFlYUTVGSVRwb182OW1BNFhDVDdFdw==
kind: Secret
metadata:
  creationTimestamp: null
  name: example-id
  namespace: upbound-system

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucketSignedURLKey
metadata:
  name: example
spec:
  forProvider:
    name: example
    backendBucketRef:
      name: example-backend-key
    keyValueSecretRef:
      key: attribute.b64_url
      name: example-id
      namespace: upbound-system
