apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example-backend
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example-backend
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Contains beautiful images
    enableCdn: true
