apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  name: example
spec:
  forProvider:
    image: debian-9-stretch-v20200805
    labels:
      environment: dev
    physicalBlockSizeBytes: 4096
    type: pd-ssd
    zone: us-central1-a
  providerConfigRef:
    name: default
