apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  name: example
spec:
  forProvider:
    image: debian-11-bullseye-v20220719
    labels:
      environment: dev
    physicalBlockSizeBytes: 4096
    type: pd-ssd
    zone: us-central1-a
  providerConfigRef:
    name: default
