apiVersion: compute.gcp.upbound.io/v1beta1
kind: ExternalVPNGateway
metadata:
  name: example
spec:
  forProvider:
    description: An externally managed VPN gateway
    interface:
      - id: 0
        ipAddress: 8.8.8.8
    redundancyType: SINGLE_IP_INTERNALLY_REDUNDANT
  providerConfigRef:
    name: default
