apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allow:
    - protocol: icmp
    - ports:
      - "80"
      - "8080"
      - 1000-2000
      protocol: tcp
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    sourceTags:
    - web
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider: {}
  providerConfigRef:
    name: default
