apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  labels:
    testing.upbound.io/example-name: example_firewall
  name: example-firewall-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    allow:
    - protocol: icmp
    - ports:
      - "80"
      - "8080"
      - 1000-2000
      protocol: tcp
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_firewall_network
    sourceTags:
    - web
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: example_firewall_network
  name: example-firewall-network-${Rand.RFC1123Subdomain}
spec:
  forProvider: {}
