apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceGroup
metadata:
  name: example
spec:
  forProvider:
    description: Terraform test instance group
    networkRef:
      name: example
    zone: us-central1-a
  providerConfigRef:
    name: default
