apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: example
spec:
  forProvider:
    machineType: e2-medium
    zone: us-central1-a
    labels:
      managed-by: crossplane
    networkInterface:
      - network: default
    bootDisk:
      - initializeParams:
          - image: debian-cloud/debian-11
