apiVersion: compute.gcp.upbound.io/v1beta1
kind: ManagedSSLCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/managedsslcertificate
  labels:
    testing.upbound.io/example-name: managed-ssl-certificate
  name: managed-ssl-certificate
spec:
  forProvider:
    managed:
    - domains:
      - example.com.
