apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkPeering
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    peerNetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: other

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    autoCreateSubnetworks: false

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: other
  name: other
spec:
  forProvider:
    autoCreateSubnetworks: false
