apiVersion: compute.gcp.upbound.io/v1beta1
kind: NodeTemplate
metadata:
  labels:
    testing.upbound.io/example-name: template
  name: template
spec:
  forProvider:
    # https://cloud.google.com/compute/docs/nodes/sole-tenant-nodes#node_types
    nodeType: c2-node-60-240
    region: us-central1
