apiVersion: compute.gcp.upbound.io/v1beta1
kind: PerInstanceConfig
metadata:
  labels:
    testing.upbound.io/example-name: per-instance-config
  name: per-instance-config
spec:
  forProvider:
    instanceGroupManagerSelector:
      matchLabels:
        testing.upbound.io/example-name: per-instance-config
    name: instance-1
    preservedState:
    - disk:
      - deviceName: per-instance-config
        mode: READ_ONLY
        sourceSelector:
          matchLabels:
            testing.upbound.io/example-name: per-instance-config
      # Preserved metadata defined for this instance. This is a list of key->value pairs
      metadata:
        foo: bar
    zone: us-central1-a

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  labels:
    testing.upbound.io/example-name: per-instance-config
  name: per-instance-config
spec:
  forProvider:
    image: debian-11-bullseye-v20220719
    physicalBlockSizeBytes: 4096
    type: pd-ssd
    zone: us-central1-a

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceGroupManager
metadata:
  labels:
    testing.upbound.io/example-name: per-instance-config
  name: per-instance-config
spec:
  forProvider:
    baseInstanceName: per-instance-config
    description: Terraform test instance group manager
    targetSize: 2
    version:
    - instanceTemplateSelector:
        matchLabels:
          testing.upbound.io/example-name: per-instance-config
      name: prod
    zone: us-central1-a

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: InstanceTemplate
metadata:
  labels:
    testing.upbound.io/example-name: per-instance-config
  name: per-instance-config
spec:
  forProvider:
    canIpForward: false
    disk:
    - autoDelete: true
      boot: true
      sourceImage: debian-cloud/debian-11
    machineType: e2-medium
    name: my-template
    networkInterface:
    - network: default
    serviceAccount:
    - scopes:
      - userinfo-email
      - compute-ro
      - storage-ro
    tags:
    - foo
    - bar
