apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionDisk
metadata:
  labels:
    testing.upbound.io/example-name: region-disk
  name: region-disk
spec:
  forProvider:
    physicalBlockSizeBytes: 4096
    region: us-central1
    replicaZones:
    - us-central1-a
    - us-central1-f
    type: pd-ssd
