apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionBackendService
metadata:
  labels:
    testing.upbound.io/example-name: region-backend-service
  name: region-backend-service
spec:
  forProvider:
    connectionDrainingTimeoutSec: 10
    healthChecksRefs:
    - name: region-backend-service
    region: us-central1
    sessionAffinity: CLIENT_IP

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionHealthCheck
metadata:
  labels:
    testing.upbound.io/example-name: region-backend-service
  name: region-backend-service
spec:
  forProvider:
    checkIntervalSec: 1
    tcpHealthCheck:
    - port: 80
    timeoutSec: 1
    region: us-central1
