apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterInterface
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/routerinterface
    upjet.upbound.io/manual-intervention: "Provider produced inconsistent result after apply"
  labels:
    testing.upbound.io/example-name: router-interface
  name: router-interface
spec:
  forProvider:
    ipRange: 169.254.1.1/30
    name: router-interface
    region: us-central1
    router: router-interface
    vpnTunnel: router-interface
