apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  labels:
    testing.upbound.io/example-name: example_router
  name: example-router-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    region: us-central1
    bgp:
    - advertiseMode: CUSTOM
      advertisedGroups:
      - ALL_SUBNETS
      advertisedIpRanges:
      - range: 1.2.3.4
      - range: 6.7.0.0/16
      asn: 64514
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_router_network
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  labels:
    testing.upbound.io/example-name: example_router_network
  name: example-router-network-${Rand.RFC1123Subdomain}
spec:
  forProvider: {}
