apiVersion: compute.gcp.upbound.io/v1beta1
kind: SharedVPCServiceProject
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/sharedvpcserviceproject
    upjet.upbound.io/manual-intervention: "Only supports this permission at project or organizational level currently"
  labels:
    testing.upbound.io/example-name: shared-vpc-service-project
  name: shared-vpc-service-project
spec:
  forProvider:
    hostProject: host-project-id
    serviceProject: service-project-id-1
