apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetPool
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targetpool
  labels:
    testing.upbound.io/example-name: target-pool
  name: target-pool
spec:
  forProvider:
    region: us-central1
    # Only legacy HTTPHealthCheck is supported
    healthChecksSelector:
      matchLabels:
        testing.upbound.io/example-name: target-pool
    # The instances need not exist at the time of target pool creation
    instances:
    - us-central1-a/target-pool

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: HTTPHealthCheck
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targetpool
  labels:
    testing.upbound.io/example-name: target-pool
  name: target-pool
spec:
  forProvider:
    checkIntervalSec: 1
    requestPath: /health_check
    timeoutSec: 1
