apiVersion: gcp.upbound.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  projectID: official-provider-testing
  credentials:
    source: Secret
    secretRef:
      name: provider-creds
      namespace: crossplane-system
      key: creds
