apiVersion: accesscontextmanager.gcp.upbound.io/v1alpha1
kind: AccessPolicyIAMPolicy
metadata:
  name: example
spec:
  forProvider:
    name: ${google_access_context_manager_access_policy.access-policy.name}
    policyData: ${data.google_iam_policy.admin.policy_data}
  providerConfigRef:
    name: example
