apiVersion: privateca.gcp.upbound.io/v1alpha1
kind: CAPool
metadata:
  name: example
spec:
  forProvider:
    labels:
      foo: bar
    location: us-central1
    name: my-pool
    publishingOptions:
    - publishCaCert: true
      publishCrl: true
    tier: ENTERPRISE
  providerConfigRef:
    name: example
