apiVersion: notebooks.gcp.upbound.io/v1alpha1
kind: Runtime
metadata:
  name: example
spec:
  forProvider:
    accessConfig:
    - accessType: SINGLE_USER
      runtimeOwner: admin@hashicorptest.com
    location: us-central1
    name: notebooks-runtime
    virtualMachine:
    - virtualMachineConfig:
      - dataDisk:
        - initializeParams:
          - diskSizeGb: "100"
            diskType: PD_STANDARD
        machineType: n1-standard-4
  providerConfigRef:
    name: example
