apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZone
metadata:
  name: example
spec:
  forProvider:
    description: Example DNS zone
    dnsName: example-${random_id.rnd.hex}.com.
    labels:
      foo: bar
