apiVersion: cloudscheduler.gcp.upbound.io/v1beta1
kind: Job
metadata:
  labels:
    testing.upbound.io/example-name: job
  name: job
spec:
  forProvider:
    description: test job
    pubsubTarget:
    - data: ${base64encode("test")}
      topicNameSelector:
        matchLabels:
          testing.upbound.io/example-name: topic
    schedule: '*/2 * * * *'

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}

---

